version: '2'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: jetlinks-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=jetlinks
      - RABBITMQ_ERLANG_COOKIE=jetlinks
    ports:
      - "15672:15672"
      - "5672:5672"